apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waiter
rules:
  - apiGroups: [""]
    resources: ["services","pods","jobs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
