apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakepostmark
  labels:
    app: fakepostmark
  annotations:
    checksum/env: {{ .Values.fakePostmarkRustLog | sha256sum }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fakepostmark
  template:
    metadata:
      labels:
        app: fakepostmark
    spec:
      containers:
        - name: fakepostmark 
          image: fakepostmark:latest
          imagePullPolicy: Never
          env:
            - name: PORT 
              value: {{ quote .Values.fakePostmarkPort }}
            - name: POSTMARK_SERVER_TOKEN
              value: {{ quote .Values.fakePostmarkToken }}
            - name: "RUST_LOG"
              value: "trace"
          ports:
            - containerPort: {{ .Values.fakePostmarkPort }} 
