apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waiter
subjects:
  - kind: ServiceAccount
    name: waiter
roleRef:
  kind: Role
  name: waiter
  apiGroup: rbac.authorization.k8s.io
