apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zero2prod-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: zero2prod-service
            port:
              number: {{ .Values.zero2prod.port }}
