repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami 
  - name: grafana
    url: https://grafana.github.io/helm-charts 

releases:
  - name: loki
    chart: grafana/loki
    namespace: telemetry
    version: 6.19.0
    values: 
      - demo/loki-values.yaml
  - name: alloy
    chart: grafana/alloy
    version: 0.10.0
    namespace: telemetry
    values:
      - demo/alloy-values.yaml
  - name: grafana
    chart: grafana/grafana
    version: 8.6.0
    namespace: telemetry
  - name: mimir
    chart: grafana/mimir-distributed
    version: 5.5.1
    namespace: mimir
  - name: postgresql
    chart: bitnami/postgresql
    namespace: db
    version: 16.1.2
    values:
      - fullnameOverride: postgres
        metrics:
          enabled: true
        auth:
          username: postgres
          password: postgrespassword
          database: newsletter
  - name: redis
    namespace: db
    chart: bitnami/redis
    version: 20.2.2
    values:
      - metrics:
          enabled: true
        fullnameOverride: redis
        architecture: standalone
        auth:
          password: redispassword

